# Generated by Django 4.0.2 on 2022-02-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_images_data_alter_minutes_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minMos', models.FloatField(default=3)),
                ('maxMos', models.FloatField(default=5)),
            ],
        ),
    ]
